trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  pythonVersion: '3.9'
  venvPath: '$(Build.SourcesDirectory)/venv'

stages:
  - stage: SetupEnvironment
    displayName: 'Set Up Environment'
    jobs:
      - job: Setup
        displayName: 'Setting up Python environment'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: $(pythonVersion)
          - script: |
              echo "Creating virtual environment..."
              python -m venv $(venvPath)
              if [ ! -d "$(venvPath)" ]; then
                echo "Virtual environment creation failed."
                exit 1
              fi
              echo "Activating virtual environment..."
              source $(venvPath)/bin/activate
              echo "Upgrading pip..."
              pip install --upgrade pip
              echo "Installing dependencies from requirements.txt..."
              pip install -r requirements.txt
            displayName: 'Install Dependencies'

  - stage: RunServer
    displayName: 'Run Flask Server'
    dependsOn: SetupEnvironment
    condition: succeeded()
    jobs:
      - job: Deploy
        displayName: 'Run Flask Application'
        steps:
          - script: |
              echo "Activating virtual environment..."
              source $(venvPath)/bin/activate
              if [ $? -ne 0 ]; then
                echo "Failed to activate the virtual environment."
                exit 1
              fi
              echo "Running Flask server..."
              python server.py
            displayName: 'Run Flask Server'
